First pass at organizing the lab based on discussion
retaildevcrews/akdc pull request #7
Opened 2021-01-07 21:18 UTC by AAkindele

# Purpose of PR

This breaks out the "Install Kubernetes" section into multiple sections. TODOs have been added where I think we can include some high level notes to provide context and also help during interactive sessions.

## Type of PR

- [x] Documentation changes
- [ ] Code changes
- [ ] Test changes
- [ ] CI-CD changes

## Validation

- [ ] Unit tests updated and ran successfully
- [ ] Documentation updated

## Issues Closed or Referenced

2021-01-08 00:02 UTC, bartr commented on Lab.md
> +
since we're using containerd, the images won't appear in a docker images command

the CLI for containerd that will show them - not sure

2021-01-08 00:02 UTC, bartr approved these changes

2021-01-12 06:28 UTC, bartr commented on Lab.md
> +
list some other choices and hyper link?

2021-01-12 06:29 UTC, bartr commented on Lab.md
> +
is it a "walkthrough"? "implementation"? something else?

does the "onboarding" concept apply here?

2021-01-12 06:34 UTC, bartr commented on Lab.md
> +
It would be really helpful to have instructions / script that will merge the cluster credentials with your local .kube/config so that you can run k locally against the Dev Cluster

2021-01-12 11:42 UTC, joaquinrz requested changes

2021-01-12 11:42 UTC, joaquinrz commented on Lab.md
> +Install containerd [prerequisites](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd)
We might need to fix/re-word this step for better developer experience. As I was following the instructions, my first approach was to follow the link and complete all steps in there. Then on the next instruction I see the prereqs commands again. Might be the case that we need to remove the link to the containerd website and show the necessary steps.

2021-01-12 11:42 UTC, joaquinrz commented on Lab.md
> +
I agree with Bart, I think there are ways to generate a kubeconfig file that can later be exported/merged anywhere but there might be a middle step that you will have to create a ServiceAccount. We can look at it together AK, Ill be interested to pair with you on this.

2021-01-12 11:55 UTC, joaquinrz commented
@bartr @AAkindele. As I was following the setup instructions for the first time, some things I noticed that grabbed my attention (mostly centered around dev experience):
- Creating a VM takes up some waiting time, I wasn't sure how long it was going to take or if I needed to cancel the process. It took around 6~8 minutes, we might want to include a note on this
- After we ssh into the VM, there is a step for logging into azure, I did not see using azure anywhere after that. I also tried to complete the instructions without logging to azure and was successful. It might be worth to consider removing this step.
- I followed the instructions for Installing the Metal Load Balancer. The instructions say that is necessary if I want to expose a public IP. After following the instructions I felt there was something missing. A ConfigMap was created but what does that do? And how does that help me expose a public IP?

I will be happy to make the changes listed above in a new PR, just need your opinion. Thanks!

2021-01-12 16:51 UTC, bartr commented on Lab.md
> +Install containerd [prerequisites](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd)
I removed the link

2021-01-12 16:56 UTC, bartr commented
- added a "this takes 5 minute note"
- removed the login to azure in lab.md
  - it's still an optional step in validation
- clarified the metal LB instructions
  - setting up an LB is an app deployment step

> * Creating a VM takes up some waiting time, I wasn't sure how long it was going to take or if I needed to cancel the process. It took around 6~8 minutes, we might want to include a note on this
> * After we ssh into the VM, there is a step for logging into azure, I did not see using azure anywhere after that. I also tried to complete the instructions without logging to azure and was successful. It might be worth to consider removing this step.
> * I followed the instructions for Installing the Metal Load Balancer. The instructions say that is necessary if I want to expose a public IP. After following the instructions I felt there was something missing. A ConfigMap was created but what does that do? And how does that help me expose a public IP?

2021-01-12 17:20 UTC, joaquinrz approved these changes

2021-01-13 21:51 UTC, AAkindele commented on Lab.md
> +
i don't have a strong preference here. maybe "learning lab" like the root readme?

2021-01-13 21:52 UTC, AAkindele commented on Lab.md
> +
i like it. i think we should definitely add it even if we can't get to it before the session.

2021-01-13 21:53 UTC, merged